### PR TITLE
Remove implicit truncation of some coordinates to integers

### PR DESCRIPTION
**Pull request by lexi-lambda**
I know you said you’d open a PR yourself, @mflatt, but I made the change locally, anyway, and I figured I might as well open the PR. Feel free to make a different change if you would like.

### CODE REVIEW

**Comment by mflatt** [comment]
Thanks! I didn't have documentation changes in mine, so that's much better in yours.

But I think your `dash-line` implementation lost a significant property. If you try the `(vline 5 40 #:segment 5)` example from the docs, your revised `dash-line` doesn't end with a dot. The old `dash-line` achieved that effect by always drawing the last segment, even if it's length is 0.

**Comment by lexi-lambda** [comment]
Yes, you’re right. I noticed that, too, but I wasn’t actually certain if that was an intentional behavior or not. I can add it back.

**Comment by lexi-lambda** [comment]
Okay, I’ve pushed a modified commit that I think is completely faithful to the old `dash-line`. That implementation has some other weirdness—for example, this is what you get if you draw `(linewidth 2 (hline 99.9 5 #:segment 10))`:

Screen Shot 2020-06-03 at 20 03 47

The last segment is much too long, which seems odd to me, but at least now it’s consistently odd.

**Comment by rfindler** [comment]
Thinking in terms of invariants and dashed lines, if we want the dash to (mostly) have a fixed size then we have to choose between the end of the line not being drawn or the last dash being too long. (Maybe this choice could be a parameter?)

**Comment by lexi-lambda** [comment]
> Thinking in terms of invariants and dashed lines, if we want the dash to (mostly) have a fixed size then we have to choose between the end of the line not being drawn or the last dash being too long.

You could also conceivably draw a normal-sized segment, but terminate the line in a point, which is what currently happens when the remainder is exactly zero.

**Comment by mflatt** [comment]
I agree that this PR now matches the old behavior, and that's probably best (if not the prettiest).

@rfindler I was going to pull you in this discussion, anyway, since the change is a kind of backward incompatibility. I've tried some slideshows programs and paper renderings, and while I confirm that the PR makes a difference in terms of alignment, it's not one I can perceive looking at the slides or papers, so I'm ok with the change.

If we're all ok with removing truncation, the PR LGTM.

**Comment by rfindler** [comment]
> > Thinking in terms of invariants and dashed lines, if we want the dash to (mostly) have a fixed size then we have to choose between the end of the line not being drawn or the last dash being too long.
> 
> You could also conceivably draw a normal-sized segment, but terminate the line in a point, which is what currently happens when the remainder is exactly zero.

So the last space would be larger?

**Comment by rfindler** [comment]
I ran a number of talks and I can't detect any difference in them. Thanks for asking!

**Comment by lexi-lambda** [comment]
> So the last space would be larger?

No, it would look like this:

Screen Shot 2020-06-03 at 22 40 36

But I realize I don’t really love either of these approaches. A nicer approach would be to arrange so the first and last segments are always of equal length (and usually smaller than the segment size), while all the other segments are exactly the segment size. That way, you satisfy both properties:

1. There is “ink” at both the start and end points of the line.

2. Given an infinitely-long dashed line of equal-length dashes, the line we draw is a segment of that line.

Here are examples of what the algorithm I am describing would produce, given a constant segment length but varying line lengths:

Screen Shot 2020-06-03 at 22 57 25

As an added bonus of this approach, the resulting line is always symmetrical, so it never looks particularly “unbalanced.” I like this approach, but it would be different, and it’s somewhat outside the scope of this change.

**Comment by rfindler** [comment]
That algorithm for drawing the lines seems like a nice one. It won't work
well for animations but in other situations it will.

**Comment by lexi-lambda** [comment]
Agreed. If I (or anyone else) were to add it to pict itself, it would make sense to add it as a keyword argument.

**Comment by samth** [comment]
This change broke some redex bitmap tests, which probably means the images just need to be re-generated. I don't know how to do that myself, but I'm sure @rfindler does.

**Comment by rfindler** [comment]
Strangely enough, it seems to have affected only one of the bitmaps.

**Pull request merged**
