### PR TITLE
contracts for dingbats

### PR DESCRIPTION
**Pull request by bennn**
For #26 

Add contracts to the pict dingbats constructors, also:
- document the `stem-color` argument of `jack-o-lantern`
- fix typos in the `thermometer` documentation

### CODE REVIEW

**Comment by stamourv** [comment]
Tests?

**Comment by rfindler** [comment]
Not that I mind the change, but is there a reason to prefer `(>/c 0)` to `positive-real?` ? (Should I make those be the same thing internally?)

**Comment by bennn** [comment]
`(>/c 0)` is clickable; there's no `positive-real?` in the docs. If there was, I would prefer that -- you should add it! (`nonnegative-real?` would also be useful)

**Comment by rfindler** [comment]
Ah. I thought it was a function already. Sorry!

I see there is a function called `positive?` but it doesn't seem helpful here because it raises an error on non-`real?`s.

**Comment by bennn** [comment]
Added tests (and realized the initial PR didn't include a contract for `desktop-machine` !).

Also, changed `thermometer` to use `exact-round` ([`utils.rkt`, L472](https://github.com/racket/pict/pull/27/files#diff-203f2f7a2e18e5495e3177cd92c11f4fR472)). With just `round`, the call to `(make-object color% ....)` on the next line was raising errors for calls like `(thermometer #:height-% 1 #:color-% 0.8)`.

**Comment by rfindler** [comment]
LGTM.

**Pull request merged**
