### PR TITLE
Fix panbox child order of operations

### PR DESCRIPTION
**Pull request by florence**
Current taking the panorama of a pict that has been rotated 180 degrees doubles the pict's width:

```
> (pict-width (rotate (rectangle 10 10) pi))
10.000000000000002
> (pict-width (panorama (rotate (rectangle 10 10) pi)))
20.000000000000004
```

It looks to me like the `panorama-box!` isn't handling the child picts correctly: with affine transformations the origin shiftings happens after the linear part of the transform (`Ax+b` not `A(x+b)`). But I don't have a good understanding of the child-model so I would love a second pair of eyes here.

### CODE REVIEW

**Comment by florence** [comment]
Thinking more about this code, I'm wondering why `panorama-box!` doesn't account for the syx and sxy components of the children, and makes me wonder if `panorama` and `shear` will compose improperly... I'll investigate and open a new issue/PR once it seems like this is the right change to make here.

**Comment by blerner** [comment]
I suspect this is related, but:
image
The first five results make sense.  The last two seem wrong to me.

**Comment by florence** [comment]
assuming smash is:
```
(define (smash p)
  (let ([x (p:blank)])
    (p:refocus (p:cc-superimpose x p) x)))
```

I think this is actually an instance of: https://github.com/racket/pict/issues/29

`(scale p -1 1)` gives a negative bounding box, which probably confuses the hell out of... well everything. (If you inset the final pict by a large amount you can see it's drawing something pretty non-sensicle.) The example also draw the same with and without this patch.

**Comment by blerner** [comment]
Ah yes.  (Pyret hit the same issue in its image library.  Bounding box dimensions are lengths, not merely the differences between two coordinates...)  I thought it might be related to this current issue because your current fix is a general transformation means that it shouldn't be limited to just `rotate`.

Weirdly(?), the original example doesn't continue in a uniform way:
```
> (pict-width (rotate (rectangle 10 10) pi))
10.000000000000002
> (pict-width (panorama (rotate (rectangle 10 10) pi)))
20.000000000000004
> (pict-width (panorama (rotate (rotate (rectangle 10 10) pi) pi)))
10.000000000000005
> (pict-width (rotate (panorama (rotate (rectangle 10 10) pi)) pi))
20.000000000000007
> (pict-width (panorama (rotate (panorama (rotate (rectangle 10 10) pi)) pi)))
40.000000000000014
```

**Comment by florence** [comment]
The original issue would only occur if an images bottom left corner was moved, and it was scaled at the same time, which scale doesn't do. In fact from a grep for the uses `make-child`, it looks like *only* rotate does this. (which explains why it wasn't noticed for so long).

**Comment by mflatt** [comment]
LGTM

**Pull request merged**
